version: "3.9"
services:
  dtn-base:
    image: dtn-base:1.0.0
    network_mode: "host"
    container_name: "${NODE_ID}-core"
    build:
      context: ./dtn-base
      dockerfile: Dockerfile
    environment:
      - name=value
      - NODE_ID
      - NODE_LOCAL_IP
      - NODE_ENDPOINT
  dtn-agent:
    image: dtn-agent:1.0.0
    network_mode: "host"
    container_name: "${NODE_ID}-agent"
    build:
      context: ./dtn-agent-server
      dockerfile: Dockerfile
    environment:
      - NODE_ID
      - NODE_LOCAL_IP
      - NODE_ENDPOINT
      - AGENT_PORT
      - MASTER_CLIENT_URL=http://localhost:3000
    stdin_open: true
    tty: true
    depends_on:
      - dtn-base

    # Add any necessary configuration here
